import assert from 'node:assert/strict';
import test from 'node:test';

import { dispatchAdminLoginRequest, dispatchAdminSessionRequest } from '../src/server/admin_auth_mode_dispatch_v1.js';
import { dispatchSensitiveReviewListRequest } from '../src/server/admin_sensitive_review_mode_dispatch_v1.js';
import {
  handleProductionAdminLoginRequest,
  handleProductionAdminLogoutRequest,
  handleProductionAdminSessionRequest,
} from '../src/server/production_admin_auth_http_v1.js';
import { ProductionAdminAuthError, readProductionAdminAuthConfig } from '../src/server/production_admin_auth_v1.js';
import {
  handleProductionSensitiveReviewApproveRequest,
  handleProductionSensitiveReviewDetailRequest,
  handleProductionSensitiveReviewEditAndApproveRequest,
  handleProductionSensitiveReviewListRequest,
  handleProductionSensitiveReviewRejectRequest,
} from '../src/server/production_admin_sensitive_review_http_v1.js';
import {
  ProductionAdminSensitiveReviewError,
  readProductionAdminSensitiveReviewConfig,
} from '../src/server/production_admin_sensitive_review_v1.js';

const BASE_NOW = 1_784_620_000_000;
const ADMIN_ORIGIN = 'https://admin.example.invalid';
const USER_ORIGIN = 'https://app.example.invalid';
const PASSWORD = 'stage7t-admin-password-0123456789-ABCDEFG';
function secret(label){return `${label}_${'q'.repeat(40)}`;}
function env(overrides={}){return{
  CLOUD_PRODUCTION_ENABLED:'1',CLOUD_PRODUCTION_READ_SYNC_ENABLED:'1',CLOUD_PRODUCTION_ORDINARY_SUBMISSION_ENABLED:'1',CLOUD_PRODUCTION_AUTO_APPROVAL_ENABLED:'1',CLOUD_PRODUCTION_SENSITIVE_SUBMISSION_ENABLED:'1',CLOUD_PRODUCTION_ADMIN_REVIEW_ENABLED:'1',CLOUD_ADMIN_PRODUCTION_ENABLED:'1',CLOUD_PRODUCTION_BOOTSTRAP_ENABLED:'0',CLOUD_PRODUCTION_BOOTSTRAP_CONFIRMATION:'',
  CLOUD_PRODUCTION_EXTERNAL_CLUB_ID:'see',CLOUD_PRODUCTION_EXTERNAL_LIBRARY_ID:'see_cz',CLOUD_PRODUCTION_GROUP_ID:'group_see',CLOUD_PRODUCTION_LIBRARY_ID:'lib_see_cz',CLOUD_PRODUCTION_BLOB_STORE_NAME:'cloud-collab-production-v1',CLOUD_ADMIN_PRODUCTION_BLOB_STORE_NAME:'cloud-collab-admin-production-v1',CLOUD_PRODUCTION_PUBLIC_ORIGIN:USER_ORIGIN,CLOUD_ADMIN_PUBLIC_ORIGIN:ADMIN_ORIGIN,CLOUD_ADMIN_USERNAME:'xiaxue',CLOUD_ADMIN_PASSWORD:PASSWORD,
  CLOUD_PRODUCTION_CLIENT_ACCESS_KEY:secret('client'),CLOUD_PRODUCTION_RATE_LIMIT_SALT:secret('public-rate'),CLOUD_ADMIN_SESSION_SECRET:secret('session'),CLOUD_ADMIN_RATE_LIMIT_SALT:secret('admin-rate'),CLOUD_ADMIN_DEVICE_REF_SALT:secret('device-ref'),CLOUD_ADMIN_ROLLBACK_REF_SALT:secret('rollback-ref'),CLOUD_ADMIN_EXPORT_AUDIT_SALT:secret('export-audit'),...overrides};}
function disabledEnv(){return env({CLOUD_PRODUCTION_ENABLED:'0',CLOUD_PRODUCTION_READ_SYNC_ENABLED:'0',CLOUD_PRODUCTION_ORDINARY_SUBMISSION_ENABLED:'0',CLOUD_PRODUCTION_AUTO_APPROVAL_ENABLED:'0',CLOUD_PRODUCTION_SENSITIVE_SUBMISSION_ENABLED:'0',CLOUD_PRODUCTION_ADMIN_REVIEW_ENABLED:'0',CLOUD_ADMIN_PRODUCTION_ENABLED:'0',CLOUD_PRODUCTION_PUBLIC_ORIGIN:'',CLOUD_ADMIN_PUBLIC_ORIGIN:'',CLOUD_ADMIN_PASSWORD:'',CLOUD_PRODUCTION_CLIENT_ACCESS_KEY:'',CLOUD_PRODUCTION_RATE_LIMIT_SALT:'',CLOUD_ADMIN_SESSION_SECRET:'',CLOUD_ADMIN_RATE_LIMIT_SALT:'',CLOUD_ADMIN_DEVICE_REF_SALT:'',CLOUD_ADMIN_ROLLBACK_REF_SALT:'',CLOUD_ADMIN_EXPORT_AUDIT_SALT:''});}
class MemoryStore{constructor(name){this.name=name;this.items=new Map();}async get(key){return this.items.has(key)?structuredClone(this.items.get(key)):null;}async setJSON(key,value,options={}){if(options.onlyIfNew&&this.items.has(key)){const e=new Error('already exists');e.code='ALREADY_EXISTS';throw e;}this.items.set(key,structuredClone(value));}async delete(key){this.items.delete(key);}}
function clock(start=BASE_NOW){let value=start;return{now(){value+=2000;return value;}};}
function adminRequest(pathname,{method='GET',body=null,cookie='',origin=ADMIN_ORIGIN}={}){const headers={Origin:origin,Referer:`${origin}/admin/`,'Sec-Fetch-Site':'same-origin'};if(cookie)headers.Cookie=cookie;if(body!==null)headers['Content-Type']='application/json';return new Request(`${ADMIN_ORIGIN}${pathname}`,{method,headers,...(body!==null?{body:JSON.stringify(body)}:{})});}
function cookiePair(value){return String(value||'').split(';')[0];}
async function login(adminStore,clk,runtimeEnv=env()){const response=await handleProductionAdminLoginRequest({env:runtimeEnv,request:adminRequest('/api/admin/auth/login',{method:'POST',body:{schemaVersion:1,username:'xiaxue',password:PASSWORD}})},{createStore:name=>{assert.equal(name,'cloud-collab-admin-production-v1');return adminStore;},now:()=>clk.now(),randomBytes:size=>Buffer.alloc(size,7)});return{response,cookie:cookiePair(response.headers.get('set-cookie'))};}

test('正式管理员与敏感审核配置使用双Store和固定作用域',()=>{const auth=readProductionAdminAuthConfig(env());assert.equal(auth.storeName,'cloud-collab-admin-production-v1');assert.equal(auth.publicStoreName,'cloud-collab-production-v1');assert.equal(auth.publicOrigin,ADMIN_ORIGIN);assert.equal(auth.capabilities.sensitiveReview,true);assert.equal(auth.capabilities.deviceMutation,false);assert.equal(auth.capabilities.rollback,false);assert.equal(auth.capabilities.export,false);assert.equal(auth.capabilities.stablePromotionAuthorized,false);const review=readProductionAdminSensitiveReviewConfig(env());assert.equal(review.storeName,'cloud-collab-production-v1');assert.equal(review.groupId,'group_see');assert.equal(review.libraryId,'lib_see_cz');assert.deepEqual(review.externalScope,{clubId:'see',libraryId:'see_cz'});});

test('关闭状态失败关闭',()=>{assert.throws(()=>readProductionAdminAuthConfig(disabledEnv()),e=>e instanceof ProductionAdminAuthError&&e.code==='PRODUCTION_ADMIN_DISABLED');assert.throws(()=>readProductionAdminSensitiveReviewConfig(env({CLOUD_PRODUCTION_SENSITIVE_SUBMISSION_ENABLED:'0'})),e=>e instanceof ProductionAdminSensitiveReviewError&&e.code==='PRODUCTION_ADMIN_SENSITIVE_REVIEW_DISABLED');});

test('正式登录、会话与退出使用安全Cookie',async()=>{const adminStore=new MemoryStore('admin');const clk=clock();const{response,cookie}=await login(adminStore,clk);assert.equal(response.status,200);const setCookie=response.headers.get('set-cookie');assert.match(setCookie,/HttpOnly/u);assert.match(setCookie,/Secure/u);assert.match(setCookie,/SameSite=Strict/u);assert.match(setCookie,/Path=\/api\/admin/u);assert.match(cookie,/^cloud_collab_admin_session=/u);const body=await response.json();assert.equal(body.data.username,'xiaxue');assert.equal(body.data.capabilities.sensitiveReview,true);const session=await handleProductionAdminSessionRequest({env:env(),request:adminRequest('/api/admin/auth/session',{cookie})},{createStore:()=>adminStore,now:()=>clk.now()});assert.equal(session.status,200);assert.equal((await session.json()).data.authenticated,true);const logout=await handleProductionAdminLogoutRequest({env:env(),request:adminRequest('/api/admin/auth/logout',{method:'POST',cookie})},{now:()=>clk.now()});assert.equal(logout.status,200);assert.match(logout.headers.get('set-cookie'),/Max-Age=0/u);});

test('错误来源在创建管理员Store前被阻断',async()=>{let calls=0;const response=await handleProductionAdminLoginRequest({env:env(),request:adminRequest('/api/admin/auth/login',{method:'POST',origin:'https://evil.example.invalid',body:{username:'xiaxue',password:PASSWORD}})},{createStore(){calls+=1;return new MemoryStore('unexpected');}});assert.equal(response.status,403);assert.equal(calls,0);});

test('审核列表严格分离管理员Store与公共Store',async()=>{const adminStore=new MemoryStore('admin');const publicStore=new MemoryStore('public');const clk=clock();const{cookie}=await login(adminStore,clk);const created=[];let received=null;const response=await handleProductionSensitiveReviewListRequest({env:env(),request:adminRequest('/api/admin/sensitive-reviews?limit=10',{cookie})},{createAdminStore:name=>{created.push(['admin',name]);return adminStore;},createPublicStore:name=>{created.push(['public',name]);return publicStore;},now:()=>clk.now(),async listProduction(input){received=input;return{schemaVersion:1,items:[],nextCursor:null};}});assert.equal(response.status,200);assert.deepEqual(created,[['admin','cloud-collab-admin-production-v1'],['public','cloud-collab-production-v1']]);assert.equal(received.store,publicStore);assert.equal(received.limit,10);const body=await response.json();assert.equal(body.data.administrator,'xiaxue');assert.equal(body.data.capabilities.reviewMutation,true);assert.equal(body.data.stablePromotionAuthorized,false);});

test('详情与三种人工动作传递管理员身份和公共Store',async()=>{const adminStore=new MemoryStore('admin');const publicStore=new MemoryStore('public');const clk=clock();const{cookie}=await login(adminStore,clk);const common={createAdminStore:()=>adminStore,createPublicStore:()=>publicStore,now:()=>clk.now()};let detailInput=null;const detail=await handleProductionSensitiveReviewDetailRequest({env:env(),request:adminRequest('/api/admin/sensitive-reviews/detail?id=sr_v1_test',{cookie})},{...common,async detailProduction(input){detailInput=input;return{reviewId:input.reviewId,status:'pending_review'};}});assert.equal(detail.status,200);assert.equal(detailInput.store,publicStore);assert.equal(detailInput.reviewId,'sr_v1_test');for(const [handler,key,action]of[[handleProductionSensitiveReviewApproveRequest,'approveProduction','approve'],[handleProductionSensitiveReviewRejectRequest,'rejectProduction','reject'],[handleProductionSensitiveReviewEditAndApproveRequest,'editAndApproveProduction','edit_and_approve']]){let received=null;const deps={...common};deps[key]=async input=>{received=input;return{reviewId:input.request.reviewId,status:action==='reject'?'rejected':'approved'};};const response=await handler({env:env(),request:adminRequest(`/api/admin/sensitive-reviews/${action}`,{method:'POST',cookie,body:{schemaVersion:1,reviewId:'sr_v1_test',confirmation:`CONFIRM_${action}`}})},deps);assert.equal(response.status,200);assert.equal(received.store,publicStore);assert.equal(received.administrator,'xiaxue');const body=await response.json();assert.equal(body.data.manualReview,true);assert.equal(body.data.stablePromotionAuthorized,false);}});

test('认证和审核路由按显式生产开关分发',async()=>{const adminStore=new MemoryStore('admin');const clk=clock();const production=await dispatchAdminLoginRequest({env:env(),request:adminRequest('/api/admin/auth/login',{method:'POST',body:{username:'xiaxue',password:PASSWORD}})},{production:{createStore:()=>adminStore,now:()=>clk.now(),randomBytes:size=>Buffer.alloc(size,8)}});assert.equal((await production.json()).serviceId,'cloud-collab-admin-production');const invalidSession=await dispatchAdminSessionRequest({env:{CLOUD_PRODUCTION_ENABLED:'invalid'},request:adminRequest('/api/admin/auth/session')});assert.equal(invalidSession.status,503);assert.equal((await invalidSession.json()).error.code,'PRODUCTION_FLAG_INVALID');const invalidReview=await dispatchSensitiveReviewListRequest({env:{CLOUD_PRODUCTION_ENABLED:'invalid'},request:adminRequest('/api/admin/sensitive-reviews')});assert.equal(invalidReview.status,503);assert.equal((await invalidReview.json()).error.code,'PRODUCTION_FLAG_INVALID');});
