(function(root,factory){const api=factory(root?.CloudCollabOrdinarySubmission||null);if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.CloudCollabOrdinarySync=api;})(typeof globalThis!=='undefined'?globalThis:this,function(submissionApi){
'use strict';
const BK=/^bk_v1_[A-Za-z0-9_-]{43}$/,CH=/^ch_v1_[A-Za-z0-9_-]{43}$/;
const TYPES=new Set(['playable_name','boss_profile']);
const DEVICE='dev_01JABCDEF0123456789XYZABCD',SUB='sub_01JABCDEF0123456789XYZABCD',MAX=5000;
class OrdinarySyncError extends Error{constructor(code,message,details=null,cause=null){super(message||code||'普通共享同步失败');this.name='OrdinarySyncError';this.code=code||'ORDINARY_SYNC_ERROR';this.details=details;if(cause)this.cause=cause;}}
function plain(v){return Boolean(v)&&typeof v==='object'&&!Array.isArray(v)&&Object.prototype.toString.call(v)==='[object Object]';}
function exact(v,keys){if(!plain(v))return false;const a=Object.keys(v).sort(),b=[...keys].sort();return a.length===b.length&&a.every((k,i)=>k===b[i]);}
function normalizeRecord(v){if(!exact(v,['approvedVersion','businessKey','contentHash','dataType','operation','payload']))throw new OrdinarySyncError('INVALID_ORDINARY_RECORD_FIELDS','普通共享公共记录字段无效');const dataType=String(v.dataType||'').trim().toLowerCase();if(!TYPES.has(dataType)||v.operation!=='upsert')throw new OrdinarySyncError('UNSUPPORTED_ORDINARY_RECORD','普通共享公共记录类型或操作无效');if(!BK.test(String(v.businessKey||''))||!CH.test(String(v.contentHash||''))||!Number.isSafeInteger(v.approvedVersion)||v.approvedVersion<1)throw new OrdinarySyncError('INVALID_ORDINARY_RECORD','普通共享公共记录版本或Hash无效');return Object.freeze({...v,dataType});}
async function projection({groupId,libraryId,dataType,payload}){if(!submissionApi?.buildPlayableNameSubmission||!submissionApi?.buildBossProfileSubmission)throw new OrdinarySyncError('ORDINARY_SUBMISSION_MODULE_REQUIRED','普通共享提交投影模块不可用');try{return dataType==='playable_name'?await submissionApi.buildPlayableNameSubmission({deviceId:DEVICE,submissionId:SUB,groupId,libraryId,name:payload?.name,origin:'initialBinding',clientCreatedAt:0}):await submissionApi.buildBossProfileSubmission({deviceId:DEVICE,submissionId:SUB,groupId,libraryId,bossName:payload?.bossName,paiDan:payload?.paiDan,discount:payload?.discount,origin:'initialBinding',clientCreatedAt:0});}catch(error){throw new OrdinarySyncError(error?.code||'ORDINARY_PROJECTION_INVALID','普通共享记录无法通过客户端白名单投影',error?.details||null,error);}}
async function verifyOrdinaryRecords({groupId,libraryId,records=[]}={}){if(!Array.isArray(records)||records.length>MAX)throw new OrdinarySyncError('ORDINARY_RECORD_LIMIT_INVALID','普通共享公共记录数量无效');const out=[],seen=new Set();for(const raw of records){if(!TYPES.has(String(raw?.dataType||'').trim().toLowerCase()))continue;const record=normalizeRecord(raw);if(seen.has(record.businessKey))throw new OrdinarySyncError('DUPLICATE_ORDINARY_BUSINESS_KEY','普通共享公共记录包含重复业务键');const projected=await projection({groupId,libraryId,dataType:record.dataType,payload:record.payload});if(projected.businessKey!==record.businessKey||projected.contentHash!==record.contentHash)throw new OrdinarySyncError('ORDINARY_RECORD_HASH_MISMATCH','普通共享公共记录Hash校验失败',{businessKey:record.businessKey});seen.add(record.businessKey);out.push(Object.freeze({...record,payload:projected.payload,bossId:projected.bossId}));}return Object.freeze(out);}
function conflictId(key,localHash,remoteHash){return `conf_${key.slice(-12)}_${String(localHash||'none').slice(-8)}_${String(remoteHash||'none').slice(-8)}`.slice(0,80);}
async function projectLocal({groupId,libraryId,confirmedNames=[],bossMemory=[]}){const map=new Map();for(const item of Array.isArray(confirmedNames)?confirmedNames:[]){try{const p=await projection({groupId,libraryId,dataType:'playable_name',payload:{name:item?.name??item}});if(!map.has(p.businessKey))map.set(p.businessKey,{projected:p,local:item});}catch(_){}}for(const item of Array.isArray(bossMemory)?bossMemory:[]){try{const p=await projection({groupId,libraryId,dataType:'boss_profile',payload:{bossName:item?.name??item?.bossName,paiDan:item?.paiDan,discount:item?.discount}});if(!map.has(p.businessKey))map.set(p.businessKey,{projected:p,local:item});}catch(_){}}return map;}
async function planOrdinaryMerge({groupId,libraryId,records=[],confirmedNames=[],bossMemory=[],baseHashes={}}={}){if(!plain(baseHashes))throw new OrdinarySyncError('INVALID_BASE_HASHES','普通共享本地基础Hash结构无效');const verified=await verifyOrdinaryRecords({groupId,libraryId,records}),local=await projectLocal({groupId,libraryId,confirmedNames,bossMemory}),nextBaseHashes={...baseHashes};const upserts=[],unchanged=[],preserveLocal=[],conflicts=[];for(const record of verified){const existing=local.get(record.businessKey)||null,localHash=existing?.projected?.contentHash||null,baseHash=typeof baseHashes[record.businessKey]==='string'?baseHashes[record.businessKey]:null,remoteHash=record.contentHash;if(localHash===remoteHash){unchanged.push({record,existing,baseHash,localHash,remoteHash});nextBaseHashes[record.businessKey]=remoteHash;}else if(baseHash===null&&localHash===null){upserts.push({record,existing:null,baseHash,localHash,remoteHash});nextBaseHashes[record.businessKey]=remoteHash;}else if(baseHash!==null&&localHash===baseHash){upserts.push({record,existing,baseHash,localHash,remoteHash});nextBaseHashes[record.businessKey]=remoteHash;}else if(baseHash!==null&&remoteHash===baseHash){preserveLocal.push({record,existing,baseHash,localHash,remoteHash});}else conflicts.push(Object.freeze({conflictId:conflictId(record.businessKey,localHash,remoteHash),businessKey:record.businessKey,dataType:record.dataType,baseHash,localHash,remoteHash,status:'open',record}));}return Object.freeze({records:verified,upserts:Object.freeze(upserts),unchanged:Object.freeze(unchanged),preserveLocal:Object.freeze(preserveLocal),conflicts:Object.freeze(conflicts),nextBaseHashes:Object.freeze(nextBaseHashes),counts:Object.freeze({upserts:upserts.length,unchanged:unchanged.length,preserveLocal:preserveLocal.length,conflicts:conflicts.length})});}
function applyOrdinaryMergePlan({confirmedNames=[],bossMemory=[],plan,now=Date.now()}={}){const names=(Array.isArray(confirmedNames)?confirmedNames:[]).map(x=>({...x})),bosses=(Array.isArray(bossMemory)?bossMemory:[]).map(x=>({...x}));let namesChanged=false,bossesChanged=false;for(const entry of plan?.upserts||[]){const r=entry.record;if(r.dataType==='playable_name'){const key=r.payload.name.toLocaleLowerCase('und'),i=names.findIndex(x=>String(x?.name||'').trim().toLocaleLowerCase('und')===key),next={name:r.payload.name,original:r.payload.name,timestamp:now,source:'cloudPull'};if(i>=0)names[i]=next;else names.push(next);namesChanged=true;}else if(r.dataType==='boss_profile'){const key=r.payload.bossName.toLocaleLowerCase('und'),i=bosses.findIndex(x=>String(x?.name||'').trim().toLocaleLowerCase('und')===key),next={name:r.payload.bossName,paiDan:r.payload.paiDan,discount:r.payload.discount};if(i>=0)bosses[i]=next;else bosses.push(next);bossesChanged=true;}}return Object.freeze({confirmedNames:Object.freeze(names),bossMemory:Object.freeze(bosses),namesChanged,bossesChanged});}
return Object.freeze({OrdinarySyncError,verifyOrdinaryRecords,planOrdinaryMerge,applyOrdinaryMergePlan});
});